# Generated by Django 4.2.16 on 2024-12-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('PhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(blank=True, max_length=256, null=True)),
                ('TimeStamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
