# Generated by Django 4.2.16 on 2024-12-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('PhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(blank=True, max_length=256, null=True)),
                ('TimeStamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='Photoshoot',
            fields=[
                ('PhotoshootId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
            options={
                'db_table': 'Photoshoot',
            },
        ),
    ]
