# Generated by Django 4.2.16 on 2024-12-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoshoot',
            name='LocationId',
            field=models.ForeignKey(db_column='LocationId', on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
