# Generated by Django 4.2.16 on 2024-12-04 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='PhotoGUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
