# Generated by Django 4.2.16 on 2025-02-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_photo_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ImagePath',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
