# Generated by Django 4.2.16 on 2024-12-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_location_alter_photo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='photo',
            table='Location',
        ),
    ]
