# Generated by Django 4.2.16 on 2024-12-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_location_alter_photo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='Photo',
        ),
    ]
