# Generated by Django 4.2.16 on 2025-02-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_photo_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
