# Generated by Django 4.2.16 on 2025-02-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_location_address_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Longitude',
        ),
    ]
